### ISSUE TITLE
Crash when source table for view isn't available. 

### ISSUE THREAD

**Issue by TilmanK** [agronholm/sqlacodegen#129]
Hey,

I'm trying to auto-generate sqlalchemy model definitions for a database (MSSQL) with about 250 tables and 150 views.

I don't know what my colleages did exactly, but one view misses the source table in the original database. This leads to a crash:

Traceback (most recent call last):
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
pyodbc.ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'PSExplorer.dbo.TESTSAMPLESTORIX'. (208) (SQLExecDirectW); [42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'PSExplorer.dbo.TESTSAMPLESTORIX'. (208)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\krumm-ti\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\krumm-ti\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\krumm-ti\Documents\PycharmProjects\TSL-Library\venv\Scripts\sqlacodegen.exe\__main__.py", line 7, in <module>
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlacodegen\main.py", line 47, in main
    metadata.reflect(engine, args.schema, not args.noviews, tables)
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 4621, in reflect
    Table(name, self, **reflect_opts)
  File "<string>", line 2, in __new__
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\util\deprecations.py", line 139, in warned
    return fn(*args, **kwargs)
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 563, in __new__
    metadata._remove_table(name, schema)
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 558, in __new__
    table._init(name, metadata, *args, **kw)
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 647, in _init
    self._autoload(
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 670, in _autoload
    autoload_with.run_callable(
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1653, in run_callable
    return callable_(self, *args, **kwargs)
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\engine\default.py", line 484, in reflecttable
    return insp.reflecttable(
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\engine\reflection.py", line 664, in reflecttable
    for col_d in self.get_columns(
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\engine\reflection.py", line 390, in get_columns
    col_defs = self.dialect.get_columns(
  File "<string>", line 2, in get_columns
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\engine\reflection.py", line 52, in cache
    ret = fn(self, con, *args, **kw)
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\dialects\mssql\base.py", line 2205, in wrap
    return _switch_db(
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\dialects\mssql\base.py", line 2229, in _switch_db
    return fn(*arg, **kw)
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\dialects\mssql\base.py", line 2776, in get_columns
    cursor = connection.execute(
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "c:\users\krumm-ti\documents\pycharmprojects\tsl-library\venv\lib\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'PSExplorer.dbo.TESTSAMPLESTORIX'. (208) (SQLExecDirectW); [42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'PSExplorer.dbo.TES
TSAMPLESTORIX'. (208)")
[SQL: select ident_seed('dbo.V_PSEX_TESTSAMPLESTORIX'), ident_incr('dbo.V_PSEX_TESTSAMPLESTORIX')]
(Background on this error at: http://sqlalche.me/e/13/f405)

A more graceful failure would be nice (like adding a comment to the generated code, etc.)

There error can be seen in the MS SQL Management Studio too:
Nachricht 208, Stufe 16, Status 1, Prozedur V_PSEX_TESTSAMPLESTORIX, Zeile 5 [Batchstartzeile 0]
Invalid object name 'PSExplorer.dbo.TESTSAMPLESTORIX'.
Meldung 4413, Ebene 16, Status 1, Zeile 7
Could not use view or function 'EDOC.dbo.V_PSEX_TESTSAMPLESTORIX' because of binding errors.

Abschlusszeit: 2021-02-11T12:57:14.8345646+01:00

**Comment by TilmanK** [comment]
I checked out the source code and traced the issue down. It's happening within sqlalchemy and there's no way to fix this in sqlacodegen gracefully. Hence closing the issue.
