### ISSUE TITLE
Maybe some bug? (ValueError in generators.py)

### ISSUE THREAD

**Issue by HexQuant** [agronholm/sqlacodegen#149]
Throws an error:
```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/sqlacodegen", line 33, in <module>
    sys.exit(load_entry_point('sqlacodegen==3.0.0b1', 'console_scripts', 'sqlacodegen')())
  File "/usr/lib/python3.9/site-packages/sqlacodegen/cli.py", line 58, in main
    outfile.write(generator.generate())
  File "/usr/lib/python3.9/site-packages/sqlacodegen/generators.py", line 129, in generate
    rendered_models = self.render_models(models)
  File "/usr/lib/python3.9/site-packages/sqlacodegen/generators.py", line 800, in render_models
    rendered.append(self.render_class(model))
  File "/usr/lib/python3.9/site-packages/sqlacodegen/generators.py", line 819, in render_class
    rendered_column_attributes.append(self.render_column_attribute(column_attr))
  File "/usr/lib/python3.9/site-packages/sqlacodegen/generators.py", line 892, in render_column_attribute
    rendered_column = self.render_column(column, column_attr.name != column.name)
  File "/usr/lib/python3.9/site-packages/sqlacodegen/generators.py", line 346, in render_column
    kwarg.remove('nullable')
ValueError: list.remove(x): x not in list
```

If you comment out the line 346 in generators.py:
```python
# kwarg.remove('nullable')
```
everything works without problems.

I am using:
Python 3.9
SQLAlchemy 1.4.22
sqlacodegen 3.0.0b1
pyodbc 4.0.31
FreeTD 1.2.18
SQLServer 2019

**Comment by agronholm** [comment]
Probably the same as #150. It has a discussion and a more elaborate description so I'm closing this one as a duplicate.
