### ISSUE TITLE
ValueError: `Field` default cannot be set in `Annotated` for 'num_Annotated

### ISSUE THREAD

**Issue by iicey** [agronholm/sqlacodegen#229]
AAAA$ sqlacodegen mysql+pymysql://root@localhost/test > models.py
Traceback (most recent call last):
  File "/Users/AAAA/anaconda3/envs/py39/bin/sqlacodegen", line 8, in <module>
    sys.exit(main())
  File "/Users/AAAA/anaconda3/envs/py39/lib/python3.9/site-packages/sqlacodegen/main.py", line 51, in main
    generator = CodeGenerator(metadata, args.noindexes, args.noconstraints, args.nojoined,
  File "/Users/AAAA/anaconda3/envs/py39/lib/python3.9/site-packages/sqlacodegen/codegen.py", line 368, in __init__
    self.inflect_engine = self.create_inflect_engine()
  File "/Users/AAAA/anaconda3/envs/py39/lib/python3.9/site-packages/sqlacodegen/codegen.py", line 460, in create_inflect_engine
    import inflect
  File "/Users/AAAA/anaconda3/envs/py39/lib/python3.9/site-packages/inflect/__init__.py", line 2046, in <module>
    class engine:
  File "/Users/AAAA/anaconda3/envs/py39/lib/python3.9/site-packages/inflect/__init__.py", line 3781, in engine
    def number_to_words(  # noqa: C901
  File "pydantic/decorator.py", line 36, in pydantic.decorator.validate_arguments.validate
    import sys
  File "pydantic/decorator.py", line 126, in pydantic.decorator.ValidatedFunction.__init__
    try:
  File "pydantic/decorator.py", line 259, in pydantic.decorator.ValidatedFunction.create_model
    return fun
  File "pydantic/main.py", line 972, in pydantic.main.create_model
  File "pydantic/main.py", line 204, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 488, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 419, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 534, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 633, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 776, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 451, in pydantic.fields.ModelField._get_field_info
ValueError: `Field` default cannot be set in `Annotated` for 'num_Annotated[str, FieldInfo(min_length=1, extra={})]'

**Comment by agronholm** [comment]
How do I reproduce this?

**Comment by makalekseev** [comment]
@iicey Try to upgrade pydantic to the latest version it should help

**Comment by sheinbergon** [comment]
@iicey i'm closing this issue, as now minimal repdocution example was provided. If it's still an ongoing issue that's not pydantic related, please re-open
