### ISSUE TITLE
Error using table name as secondary value in many-to-many relationships in postgreSQL

### ISSUE THREAD

**Issue by rmartico** [agronholm/sqlacodegen#54]
Generating a many-to-many relationship, the name used in the secondary parameter was the table, instead of the variable.

Example:
```
t_authoring = Table(
       'authoring', metadata,
        Column('author', ForeignKey('public.authors.author'), primary_key=True, nullable=False),
        Column('mafid', ForeignKey('public.items.mafid'), primary_key=True, nullable=False),
        schema='public'
)

class Author(Base):
    __tablename__ = 'authors'
    __table_args__ = {'schema': 'public'}
    author = Column(String(80), primary_key=True)
    items = relationship('Item', secondary='authoring')
```
If I replace `secondary='authoring' ` with `secondary=t_authoring` the problem seems solved.

**Comment by agronholm** [comment]
What is the error you get? According to SQLAlchemy documentation, passing the secondary table by its name is perfectly legit.

**Comment by rmartico** [comment]
The complete stack trace of the error, using the original generated file, in a basic test reading the table content, is:

Traceback (most recent call last):
  File "F:/desarrollo flask-ubu-novamag-17-18/ubu-flask-experiments/persistence/test_database.py", line 28, in <module>
    for instance in session.query(Atom):
  File "G:\Flask\myproject27\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1362, in query
    return self._query_cls(entities, self, **kwargs)
  File "G:\Flask\myproject27\venv\lib\site-packages\sqlalchemy\orm\query.py", line 139, in __init__
    self._set_entities(entities)
  File "G:\Flask\myproject27\venv\lib\site-packages\sqlalchemy\orm\query.py", line 150, in _set_entities
    self._set_entity_selectables(self._entities)
  File "G:\Flask\myproject27\venv\lib\site-packages\sqlalchemy\orm\query.py", line 180, in _set_entity_selectables
    ent.setup_entity(*d[entity])
  File "G:\Flask\myproject27\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3585, in setup_entity
    self._with_polymorphic = ext_info.with_polymorphic_mappers
  File "G:\Flask\myproject27\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 764, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "G:\Flask\myproject27\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1948, in _with_polymorphic_mappers
    configure_mappers()
  File "G:\Flask\myproject27\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 2872, in configure_mappers
    mapper._post_configure_properties()
  File "G:\Flask\myproject27\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1765, in _post_configure_properties
    prop.init()
  File "G:\Flask\myproject27\venv\lib\site-packages\sqlalchemy\orm\interfaces.py", line 184, in init
    self.do_init()
  File "G:\Flask\myproject27\venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 1653, in do_init
    self._process_dependent_arguments()
  File "G:\Flask\myproject27\venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 1678, in _process_dependent_arguments
    setattr(self, attr, attr_value())
  File "G:\Flask\myproject27\venv\lib\site-packages\sqlalchemy\ext\declarative\clsregistry.py", line 293, in __call__
    (self.prop.parent, self.arg, n.args[0], self.cls)
**sqlalchemy.exc.InvalidRequestError: When initializing mapper Mapper|Author|authors, expression 'authoring' failed to locate a name ("name 'authoring' is not defined"). If this is a class name, consider adding this relationship() to the <class 'persistence.novamag_search_error.Author'> class after both dependent classes have been defined.**

If I modify the code as previously has been indicated, the error dissapears.
Greetings.

**Comment by rmartico** [comment]
Hi, Alex.

You have my answer in the GitHub thread.

Kind regards,
Raúl Marticorena

De: Alex Grönholm [mailto:notifications@github.com]
Enviado el: domingo, 20 de mayo de 2018 18:57
Para: agronholm/sqlacodegen
CC: RAUL MARTICORENA SANCHEZ; Author
Asunto: Re: [agronholm/sqlacodegen] Error using table name as secondary value in many-to-many relationships in postgreSQL (#54)


What is the error you get? According to SQLAlchemy documentation, passing the secondary table by its name is perfectly legit.

**Comment by agronholm** [comment]
It seems that the problem was the lack of the explicit schema qualifier. The problem has been fixed 3 years ago.
