### ISSUE TITLE
Generates broken models for tables with FK constraints on columns named 'relationship'

### ISSUE THREAD

**Issue by nijm** [agronholm/sqlacodegen#68]
Tables with foreign key constraints on columns named 'relationship' result in broken models because the column hides the sqlalchemy.orm.relationship function.

sqlite file test.sql:
```
CREATE TABLE person (
  name varchar(50) primary key,
  relationship varchar(50),
  FOREIGN KEY(relationship) REFERENCES person(name)
);
```
Create the DB and model:
```
$ sqlacodegen --version
2.0.0
$ sqlite3 test.db < test.sql
$ sqlacodegen sqlite:///test.db > test_db.py
```
test_db.py:
```
# coding: utf-8
from sqlalchemy import Column, ForeignKey, String
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base


Base = declarative_base()
metadata = Base.metadata


class Person(Base):
    __tablename__ = 'person'

    name = Column(String(50), primary_key=True)
    relationship = Column(ForeignKey('person.name'))

    parent = relationship('Person', remote_side=[name])
```
Use the model:
```
$ python3 -m test_db
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/vagrant/test_db.py", line 10, in <module>
    class Person(Base):
  File "/vagrant/test_db.py", line 16, in Person
    parent = relationship('Person', remote_side=[name])
TypeError: 'Column' object is not callable
```

**Comment by agronholm** [comment]
Fixed via 6af0f02de75152b433c0ae2bca757d51e0387958.
