### ISSUE TITLE
Handle NullType

### ISSUE THREAD

**Issue by azatoth** [agronholm/sqlacodegen#72]
If for example a postgres field has the type "chkpass", a NullType will be generated, but it will raise a CompileError:
sqlalchemy.exc.CompileError: Can't generate DDL for NullType(); did you forget to specify a type on this Column?

see http://docs.sqlalchemy.org/en/latest/core/type_api.html#sqlalchemy.types.NullType

**Comment by francois-baptiste** [comment]
It seems this fork handle NullType better https://github.com/ksindi/flask-sqlacodegen ...

**Comment by agronholm** [comment]
If you can point out how it should be handled, I can look into implementing this.

**Comment by rachmadaniHaryono** [comment]
traceback
```console
Traceback (most recent call last):
  File "/home/q/envs/happypanda/bin/sqlacodegen", line 11, in <module>
    sys.exit(main())
  File "/home/q/envs/happypanda/lib/python3.6/site-packages/sqlacodegen/main.py", line 51, in main
    args.noinflect, args.noclasses)
  File "/home/q/envs/happypanda/lib/python3.6/site-packages/sqlacodegen/codegen.py", line 413, in __init__
    model = self.table_model(table)
  File "/home/q/envs/happypanda/lib/python3.6/site-packages/sqlacodegen/codegen.py", line 91, in __init__
    column.type = self._get_adapted_type(column.type, column.table.bind)
  File "/home/q/envs/happypanda/lib/python3.6/site-packages/sqlacodegen/codegen.py", line 94, in _get_adapted_type
    compiled_type = coltype.compile(bind.dialect)
  File "/home/q/envs/happypanda/lib/python3.6/site-packages/sqlalchemy/sql/type_api.py", line 581, in compile
    return dialect.type_compiler.process(self)
  File "/home/q/envs/happypanda/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 388, in process
    return type_._compiler_dispatch(self, **kw)
  File "/home/q/envs/happypanda/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 90, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/q/envs/happypanda/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 3307, in visit_null
    "type on this Column?" % type_
sqlalchemy.exc.CompileError: Can't generate DDL for NullType(); did you forget to specify a type on this Column?
```

**Comment by agronholm** [comment]
@rachmadaniHaryono the traceback is not useful. What I need is for someone to tell me how to reproduce this and how to fix it.

**Comment by rachmadaniHaryono** [comment]
>What I need is for someone to tell me how to reproduce this

i use this software to regenerate this db https://github.com/rachmadaniHaryono/happypanda/blob/master/version/database/db.py

i will upload empty db example later

**Comment by viewpointsa** [comment]
I' have the same problem with postgresql, and two specials type: xml, and polygon (https://www.postgresql.org/docs/11/datatype-geometric.html):
  ```
 sqlacodegen.exe "postgresql+psycopg2://user:pwd@host:5432/dbname" --outfile dbname
 c:\python27\lib\site-packages\sqlalchemy\dialects\postgresql\base.py:2963: SAWarning: Did not recognize type 'polygon' of column 'convexhull'
   "Did not recognize type '%s' of column '%s'" % (attype, name)
 Traceback (most recent call last):
   File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
     "__main__", fname, loader, pkg_name)
   File "c:\python27\lib\runpy.py", line 72, in _run_code
     exec code in run_globals
   File "C:\Python27\Scripts\sqlacodegen.exe\__main__.py", line 9, in <module>
   File "c:\python27\lib\site-packages\sqlacodegen\main.py", line 51, in main
     args.noinflect, args.noclasses)
   File "c:\python27\lib\site-packages\sqlacodegen\codegen.py", line 416, in __init__
     not nojoined)
   File "c:\python27\lib\site-packages\sqlacodegen\codegen.py", line 170, in __init__
     super(ModelClass, self).__init__(table)
   File "c:\python27\lib\site-packages\sqlacodegen\codegen.py", line 91, in __init__
     column.type = self._get_adapted_type(column.type, column.table.bind)
   File "c:\python27\lib\site-packages\sqlacodegen\codegen.py", line 94, in _get_adapted_type
     compiled_type = coltype.compile(bind.dialect)
   File "c:\python27\lib\site-packages\sqlalchemy\sql\type_api.py", line 580, in compile
     return dialect.type_compiler.process(self)
   File "c:\python27\lib\site-packages\sqlalchemy\sql\compiler.py", line 400, in process
     return type_._compiler_dispatch(self, **kw)
   File "c:\python27\lib\site-packages\sqlalchemy\sql\visitors.py", line 91, in _compiler_dispatch
     return meth(self, **kw)
   File "c:\python27\lib\site-packages\sqlalchemy\sql\compiler.py", line 3350, in visit_null
     "type on this Column?" % type_
 sqlalchemy.exc.CompileError: Can't generate DDL for NullType(); did you forget to specify a type on this Column?
```
My workarround is to exclude problematic tables, first find problematic table by column name:
```
select c.relname
from pg_class as c
    inner join pg_attribute as a on a.attrelid = c.oid
where a.attname = 'convexhull' and c.relkind = 'r'
```
then retrieve all tables from sql query :
```
SELECT *
FROM information_schema.tables
WHERE table_schema = 'public' and table_catalog = '<dbname>' 
and table_type = 'BASE TABLE' 
and table_name not in ('excludetable1','excludetable2','excludetable3')
ORDER BY table_schema,table_name;
```
And run with parameters tables:
```
 sqlacodegen.exe "postgresql+psycopg2://user:pwd@host:5432/dbname" --outfile dbname --tables table1,table2,table3
```
It the first time I use this tools but It amazing how relationship was automatically detected !

**Comment by jleaders** [comment]
Expanding on `viewpointsa`, here's for mysql:

```
# sqlacodegen mysql+mysqldb://myuser@127.0.0.1/mydb  --tables `echo 'show tables;' | mysql -u myuser -p mypassword mydb | sed 's|Tables_in_mydb||g' |tr '\n' ',' | sed 's|problemtable1,||g' | sed 's|problemtable2,||g' | sed 's/,*$//g' | sed 's|^,||g'` > outputfile.py
```

where you need to set problemtable1, problemtable2

PLEASE add an "Exclude tables' flag, because this is really tedious, or have a flag similar to  to `--skip-unknown-types` where it doesn't just choke and die when it hits unknowns

**Comment by agronholm** [comment]
Yeah, I need to do something about it crashing on unknown types. But should I just exclude the entire table or just the column?

**Comment by jleaders** [comment]
I'd do whatever `flask-sqlacodegen` does, it works, heck just look at their code.
