### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'retrieve_as_bitwise' with SQLAlchemy==1.2.15

### ISSUE THREAD

**Issue by evahteev** [agronholm/sqlacodegen#85]
Launching the sqlacodegen with latest version of SQLAlchemy==1.2.15 causes the following error:

Traceback (most recent call last):
  File "/usr/local/bin/sqlacodegen", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/sqlacodegen/main.py", line 51, in main
    args.noinflect, args.noclasses)
  File "/usr/local/lib/python2.7/dist-packages/sqlacodegen/codegen.py", line 416, in __init__
    not nojoined)
  File "/usr/local/lib/python2.7/dist-packages/sqlacodegen/codegen.py", line 170, in __init__
    super(ModelClass, self).__init__(table)
  File "/usr/local/lib/python2.7/dist-packages/sqlacodegen/codegen.py", line 91, in __init__
    column.type = self._get_adapted_type(column.type, column.table.bind)
  File "/usr/local/lib/python2.7/dist-packages/sqlacodegen/codegen.py", line 102, in _get_adapted_type
    new_coltype = coltype.adapt(supercls)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/mysql/enumerated.py", line 310, in adapt
    **kw
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 1045, in constructor_copy
    return cls(*args, **kw)
TypeError: __init__() got an unexpected keyword argument 'retrieve_as_bitwise'

After downgrading to SQLAlchemy==0.8.1 work like a charm

**Comment by zhangkaizhao** [comment]
`SQLAlchemy==0.9.*` works too. But any `SQLAlchemy>=1.0`  raises the same error above.

**Comment by yoyo-real** [comment]
I had this problem when I used the SET type in MySQL.

MySQL8
sqlalchemy==1.3.17
sqlacodegen==2.2.0

**Comment by martin-niklasson** [comment]
@yoyo-real is correct. This happens when you have a SET in MySQL. Removing the SET data type solves the problem, all other things the same

**Comment by skiwichu** [comment]
Removing SET data type is not a solution if you work with external data for instance.

**Comment by leocxy** [comment]
I have the same error message.

Downgrade the sqlAlchemy is the best solution.

```shell
>pip install "SQLAlchemy>=0.9.0,<1.0.0" --force-reinstall
>flask-sqlacodegen --flask mysql+pymysql://leo:PASSWORD@localhost:PORT/DB
```

### Current Env
- Python 3.8.5
- SQLAlchemy 1.3.20
- Flask 1.1.2

**Comment by agronholm** [comment]
@leocxy This was already fixed in the last release. If you're still having trouble, please provide details, preferably with repro instructions.

**Comment by leocxy** [comment]
@agronholm Oh, you are right. I was using the incorrect library.
