### ISSUE TITLE
KeyError: 'MYCOLUMN '

### ISSUE THREAD

**Issue by lucasrcezimbra** [agronholm/sqlacodegen#87]
I receive a KeyError running 

```
$ sqlacodegen --schema=myschema --tables=mytable 'oracle://myuser:mypassword@myhost'

Traceback (most recent call last):
  File "/home/lucas/workspace/notebooks/.venv/bin/sqlacodegen", line 11, in <module>
    sys.exit(main())
  File "/home/lucas/workspace/notebooks/.venv/lib/python3.6/site-packages/sqlacodegen/main.py", line 51, in main
    args.noinflect, args.noclasses)
  File "/home/lucas/workspace/notebooks/.venv/lib/python3.6/site-packages/sqlacodegen/codegen.py", line 403, in __init__
    if isinstance(table.c[colname].type, String):
  File "/home/lucas/workspace/notebooks/.venv/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 198, in __getitem__
    return self._data[key]
KeyError: 'MYCOLUMN '
```
```
$ sqlacodegen --schema=myschema --tables=mytable 'oracle://myuser:mypassword@myhost'

Traceback (most recent call last):
  File "/home/lucas/workspace/notebooks/.venv/bin/sqlacodegen", line 11, in <module>
    sys.exit(main())
  File "/home/lucas/workspace/notebooks/.venv/lib/python3.6/site-packages/sqlacodegen/main.py", line 51, in main
    args.noinflect, args.noclasses)
  File "/home/lucas/workspace/notebooks/.venv/lib/python3.6/site-packages/sqlacodegen/codegen.py", line 403, in __init__
    if isinstance(table.c[colname].type, String):
  File "/home/lucas/workspace/notebooks/.venv/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 198, in __getitem__
    return self._data[key]
KeyError: 'mycolumn '
```

I fixed that changing [this line](https://github.com/agronholm/sqlacodegen/blob/master/sqlacodegen/codegen.py#L401) to:

```
colname = _re_column_name.match(match.group(1)).group(3).lower().strip()
```

Does this correction make sense? Should I open a pull request with this?

**Comment by pedrozan** [comment]
Same thing happened to me, your fix worked!

**Comment by Lrcezimbra** [comment]
You can use [this](https://github.com/Lrcezimbra/sqlacodegen) with
```
pip install -e git+https://github.com/Lrcezimbra/sqlacodegen@7f31b3092f04d1074c6775bc11464944d99a97b1#egg=sqlacodegen
```

**Comment by softwarepk** [comment]
The problem is not with the upper case. It is the extra space at the end that caused the problem. A strip() alone should have worked. Converting to lower case may not desirable.

**Comment by softwarepk** [comment]
Probably a better approach is to update the column name regular expression.
`_re_column_name = re.compile(r'(?:(["`]?)(?:.*)\1\.)?(["`]?)(.*)\2')`
could be
`_re_column_name = re.compile(r'(?:(["`]?)(?:.*)\1\.)?(["`]?)([^\n ]*)\2')`

**Comment by softwarepk** [comment]
Well since column names can possibily have space in them a better regular expression could be something like
`_re_column_name = re.compile(r'(?:(["`]?)(?:.*)\1\.)?(["`]?)(.*[^\n ]+)\2')`

**Comment by Lrcezimbra** [comment]
> The problem is not with the upper case. It is the extra space at the end that caused the problem. A strip() alone should have worked. Converting to lower case may not desirable.

I tried with only strip and have same problem in other column that don't have white spaces:

```
Traceback (most recent call last):
  File ".venv/bin/sqlacodegen", line 8, in <module>
    sys.exit(main())
  File "/home/lucas/workspace/tests/.venv/lib/python3.6/site-packages/sqlacodegen/main.py", line 52, in main
    args.noinflect, args.noclasses, nocomments=args.nocomments)
  File "/home/lucas/workspace/tests/.venv/lib/python3.6/site-packages/sqlacodegen/codegen.py", line 407, in __init__
    colname = _re_column_name.match(match.group(1)).group(3).strip()
  File "/home/lucas/workspace/tests/.venv/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 194, in __getitem__
    return self._data[key]
KeyError: 'SIT_PROCESSAMENTO'
```

**Comment by softwarepk** [comment]
My concern is that changing column name to lowercase may solve the problem with Oracle but it will result in changing the column name for other databases where it may not have been required or not even desirable. Personally I would prefer to keep the column names as close to as they were in the original database.

May be we should either detect at runtime the type of database involved or we need to pass a command line parameter at that tells sqlacodegen that the database is an Oracle database and it needs special treatment with column names.

**Comment by agronholm** [comment]
Is this still relevant with 3.0.0b1?

**Comment by smurpau** [comment]
> Is this still relevant with 3.0.0b1?

Not sure what 3.0.0b1 is, but with the current pip release (2.3.0) this is absolutely required for Oracle databases. Works perfectly if I add a `.lower()` to `colname = _re_column_name.match(match.group(1)).group(3)`

**Comment by agronholm** [comment]
That means, did you try this with the 3.0.0b1 pre-release?

**Comment by smurpau** [comment]
> That means, did you try this with the [3.0.0b2](https://pypi.org/project/sqlacodegen/3.0.0b2/) pre-release?

Just did and the same error arises.

**Comment by smurpau** [comment]
^This solves the whitespace issue, but not the capitalisation issue. Can you add a test for uppercase column `'ID'` and at least a switch that we can enable, if this is an Oracle-specific issue?

**Comment by agronholm** [comment]
Are all column names always in upper case on Oracle? I have some doubts about that. If they aren't and I tweaked sqlacodegen to change the capitalization, it would no longer create the schema as it was before.

**Comment by smurpau** [comment]
No, they're not always in upper case (although that is the convention). Currently it doesn't create any schema at all.

**Comment by agronholm** [comment]
Are you still getting a `KeyError`?

**Comment by agronholm** [comment]
I think I'm not understanding the fundamental problem here.

**Comment by agronholm** [comment]
@smurpau can you post a traceback produced by the code in master?

**Comment by smurpau** [comment]
I can't actually; my organisation prevents installing from the public Github and pip won't install from a zip either. I can install from PyPI. I was getting the same KeyError as the OP here though, and it resolved when I added the `.lower`

**Comment by benridley** [comment]
I'm also hitting this. Traceback using the Pip module with an existing Postgres database:
```
Traceback (most recent call last):
  File "/home/ben/.cache/pypoetry/virtualenvs/migrations-dDPSF9IL-py3.9/bin/sqlacodegen", line 8, in <module>
    sys.exit(main())
  File "/home/ben/.cache/pypoetry/virtualenvs/migrations-dDPSF9IL-py3.9/lib/python3.9/site-packages/sqlacodegen/main.py", line 51, in main
    generator = CodeGenerator(metadata, args.noindexes, args.noconstraints, args.nojoined,
  File "/home/ben/.cache/pypoetry/virtualenvs/migrations-dDPSF9IL-py3.9/lib/python3.9/site-packages/sqlacodegen/codegen.py", line 446, in __init__
    classes[model.parent_name].children.append(model)
KeyError: 'MyTable'
```

**Comment by agronholm** [comment]
@benridley and have you tried with the latest beta?

**Comment by benridley** [comment]
@agronholm Thanks for getting back to me, the latest beta fixes the issue.
